name: C Build

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the build.

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - name: Build
      run: |
        make all
        # This command builds your project using the Makefile. Adjust if necessary.

    # Optional: Clean up
    - name: Clean (Optional)
      run: make clean
      # This step is optional and can be used to clean up any build artifacts.
